sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - google-chrome --version
  - wget https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /usr/bin/
  - echo $DISPLAY
  - gem update
  - gem install bundler
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo pip install robotframework
  - sudo pip install robotframework-selenium2library


before_script:

rvm:
  - 2.1

python:
  - 2.7
