dist: bionic
language: ruby

services:
  - xvfb

addons:
  chrome: stable

script: xvfb-run -a -e /dev/stdout bundle exec rake

before_install:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/tmp
  - export PATH=$HOME/.local/bin:$PATH:/tmp
  - gem update
  - gem install bundler
  - pip install --user --upgrade pip
  - pip install --user --upgrade urllib3
  - pip install --user robotframework
  - pip install --user robotframework-selenium2library

before_script:
  - google-chrome --version
  - ls robottests/ChromeProfiles/zh-cn/Default/

rvm:
  - 2.6.3

python:
  - 2.7
