before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo pip install robotframework
  - sudo pip install robotframework-selenium2library

language: ruby

rvm:
  - 1.9.3

python:
  - 2.7

