before_install:
  - gem update
  - gem install bundler
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo pip install robotframework=2.9.1
  - sudo pip install robotframework-selenium2library

rvm:
  - 2.1

python:
  - 2.7
