before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: ruby
rvm:
  - 1.9.3
language: python
python:
  - "2.7"
install: 
  - pip install robotframework
  - pip install robotframework-selenium2library
script: 
  - pybot --noncritical "developing" robottests
