language: ruby
cache: bundler

addons:
  chrome: stable

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /tmp
  - export PATH=$HOME/.local/bin:$PATH:/tmp
  - gem update
  - gem install bundler
  - pip install --user --upgrade pip
  - pip install --user --upgrade urllib3
  - pip install --user robotframework
  - pip install --user robotframework-selenium2library

before_script:
  - google-chrome --version
  - ls robottests/ChromeProfiles/zh-cn/Default/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

rvm:
  - 2.6.3

python:
  - 2.7
