dist: bionic
language: ruby

services:
  - xvfb

addons:
  chrome: stable

script: xvfb-run bundle exec rake

before_install:
  - wget https://chromedriver.storage.googleapis.com/2.37/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /tmp
  - export PATH=$HOME/.local/bin:$PATH:/tmp
  - gem update
  - gem install bundler
  - pip install --user --upgrade pip
  - pip install --user --upgrade urllib3
  - pip install --user robotframework
  - pip install --user robotframework-selenium2library

before_script:
  - google-chrome --version
  - ls robottests/ChromeProfiles/zh-cn/Default/

rvm:
  - 2.6.3

python:
  - 2.7
